### ISSUE TITLE
Update to 3+ version

### ISSUE THREAD

**Issue by iPOiZN** [AlexLavoie42/Nuxt-Mapbox#104]
The module uses version 2 of mapbox-gl. Many features and options are not supported. Please update to version 3. The latest version of mapbox-gl is 3.1.2.

**Comment by AlexLavoie42** [comment]
Mapbox has been on version 3.1.0 since v1.5.8 of the module
https://github.com/AlexLavoie42/Nuxt-Mapbox/blob/987b7ace4678b50145f27feab6513725997e40e3/package.json#L46

Make sure your local copy of Mapbox-gl is up to date.
