### ISSUE TITLE
Property 'setConfigProperty' does not exist on type 'Map'.ts(2339)

### ISSUE THREAD

**Issue by iPOiZN** [AlexLavoie42/Nuxt-Mapbox#105]
<img width="1189" alt="image" src="https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/94292771/00a00136-8deb-4d25-a6f1-749a7488b852">

nuxt-mapbox version 1.5.8. Need to change the card color to 'dusk'

**Comment by AlexLavoie42** [comment]
Unfortunately @types/mapbox-gl has not been updated to 3.x yet so TS will complain about this.
I have just done a PR to update it but it is just waiting for approval.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68640
