### ISSUE TITLE
Mapbox Draw polygon component 

### ISSUE THREAD

**Issue by Pierre-Saigot** [AlexLavoie42/Nuxt-Mapbox#109]
Hello,

As far as I'm aware, we currently cannot use Mapbox Draw with Nuxt Mapbox. I tried to make it work by importing the library directly alongside mapbox-nuxt, but it led to a lot of errors and incompatibilities. Is there a possibility of having Mapbox Draw as a component in the future?

Thanks in advance.

**Comment by AlexLavoie42** [comment]
I will work on adding a new component for this in the next update.

For now I was able to get it to work in the playground with `useMapbox`:

```js
import MapboxDraw from '@mapbox/mapbox-gl-draw';
import '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw.css'

useMapbox(MAP_ID, (map) => {
  const Draw = new MapboxDraw();
  map.addControl(Draw, 'top-left');
});
```

**Comment by Pierre-Saigot** [comment]
Indeed, I hadn't thought of doing it like that! Thank you.
