### ISSUE TITLE
Add MapboxDefaultMarker <slot> to attach MapboxDefaultPopup

### ISSUE THREAD

**Issue by Kalv1** [AlexLavoie42/Nuxt-Mapbox#14]
Hi!

I'm putting this down here but it would be really nice to have the ability to link a popup to a marker via a slot or props ? Just like VueMapbox does. (cf [Marker and Popups](https://soal.github.io/vue-mapbox/guide/markers&popups.html#markers-popups-together) )

From what I've seen at the moment it's not possible to link a popup to a marker in this way (unless I'm wrong). I also tried to link with geoJson but no way to make the points display like defaultMarker while my data is valid it passes on geojson.io and displays correctly.

So I propose a syntax like :
```js
<MapboxDefaultMarker v-for="item, index in geoSource.features" :lnglat="item.geometry.coordinates" :marker-id="`marker-${index}`" :options="{ color: '#FF00FF'}">
	<MapboxDefaultPopup>
		<div>
			<h3>{{ item.properties.name }}</h3>
			<p>{{ item.properties.description }}</p>
		</div>
	</MapboxDefaultPopup>
</MapboxDefaultMarker>
```

And then have the possibility to bind the click on the marker when the popup opens.

**Comment by AlexLavoie42** [comment]
This should be possible currently with the marker & popup composables in a custom component. [Here](https://docs.mapbox.com/mapbox-gl-js/example/set-popup/)  is some documentation on how to do it.

I will work on adding this feature in the next update though.

**Comment by AlexLavoie42** [comment]
Added with #16
