### ISSUE TITLE
[FeatRequest]: Control position prop for map control components

### ISSUE THREAD

**Issue by HamoBoker** [AlexLavoie42/Nuxt-Mapbox#15]
Hi

I wanted to request a feature that makes you able to add a position prop for components that adds a control on the map for example 
```vue
<MapboxNavigationControl position='bottom-right' />
```

Thank you for your amazing work 💙

**Comment by AlexLavoie42** [comment]
Added with #16

**Comment by HamoBoker** [comment]
Thank you so much 💙
