### ISSUE TITLE
The requested module '...' does not provide an export named 'default'

### ISSUE THREAD

**Issue by AlexLavoie42** [AlexLavoie42/Nuxt-Mapbox#2]
When imported into project, this error appears. Currently is fixed by removing the mapboxgl import in the plugin & using CDN import but this breaks TS in src.

Ideally this line should only be removed on build.

Related to mapbox/mapbox-gl-js#8676

**Comment by AlexLavoie42** [comment]
Fixed in #45

**Comment by LumosAgency** [comment]
This issue is still persisting for me. Is there a workaround I can do locally to correct this?

**Comment by PanagiotisKotsaris** [comment]
It is also showing up in my project. I'm using Nuxt 3.6.3, with Node 20.4 with quasar-ui and tailwind plugins installed. Other than those two plugins nothing else is changed. I have a clean new Nuxt project.

**Comment by AlexLavoie42** [comment]
Fixed in #50 
Be sure to update nuxt to `3.6.5` which was just released. There seems to have been a bug with component importing in `3.6.4`.

**Comment by PanagiotisKotsaris** [comment]
Thanks!!! The update came just in time
