### ISSUE TITLE
Error using MapboxCustomGeocoder

### ISSUE THREAD

**Issue by agracia-foticos** [AlexLavoie42/Nuxt-Mapbox#30]
![image](https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/77386602/d45cb09f-8f8a-45be-a600-2b59aff8feb4)

I have upgrade my project to 1.3.5 but use mapboxgeocoder fails

**Comment by AlexLavoie42** [comment]
See #2 

It's an issue with the mapbox module. I will attempt another workaround fix.

**Comment by AlexLavoie42** [comment]
Fixed with #32
