### ISSUE TITLE
marker dragend not working

### ISSUE THREAD

**Issue by bolokoz** [AlexLavoie42/Nuxt-Mapbox#39]
Marker `drag` event and `dragstart` are working but `dragend` isn't
`dragstart` emit is duplicated in the marker component. I tried fixing it but didn't work

<img width="469" alt="image" src="https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/4869696/f0b97616-ee33-49c2-a4de-1321afa37fec">

**Comment by AlexLavoie42** [comment]
Fixed in #45
