### ISSUE TITLE
error on second navigateto

### ISSUE THREAD

**Issue by agracia-foticos** [AlexLavoie42/Nuxt-Mapbox#43]
We have this reproduction link:

https://stackblitz.com/edit/nuxt-starter-hjvw8o

If you navigate through the links, first navigateTo runs, but the second fails:

I remove nuxt-mapbox and runs

Error in console:
`chunk-MNWBZQKJ.js:82 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (chunk-MNWBZQKJ.js:82:30)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-3Q27KRJ5.js:5823:11)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (chunk-3Q27KRJ5.js:5860:52)
    at updateComponent (chunk-3Q27KRJ5.js:5687:18)
    at processComponent (chunk-3Q27KRJ5.js:5622:7)
    at patch (chunk-3Q27KRJ5.js:5084:11)
    at sharedContext.activate (chunk-3Q27KRJ5.js:2485:7)
    at processComponent (chunk-3Q27KRJ5.js:5603:29)
    at patch (chunk-3Q27KRJ5.js:5084:11)
parentNode @ chunk-MNWBZQKJ.js:82
componentUpdateFn @ chunk-3Q27KRJ5.js:5823
run @ reactivity.esm-bundler.js:178
instance.update @ chunk-3Q27KRJ5.js:5860
updateComponent @ chunk-3Q27KRJ5.js:5687
processComponent @ chunk-3Q27KRJ5.js:5622
patch @ chunk-3Q27KRJ5.js:5084
sharedContext.activate @ chunk-3Q27KRJ5.js:2485
processComponent @ chunk-3Q27KRJ5.js:5603
patch @ chunk-3Q27KRJ5.js:5084
patchSuspense @ chunk-3Q27KRJ5.js:1326
process @ chunk-3Q27KRJ5.js:1129
patch @ chunk-3Q27KRJ5.js:5109
componentUpdateFn @ chunk-3Q27KRJ5.js:5819
run @ reactivity.esm-bundler.js:178
instance.update @ chunk-3Q27KRJ5.js:5860
updateComponent @ chunk-3Q27KRJ5.js:5687
processComponent @ chunk-3Q27KRJ5.js:5622
patch @ chunk-3Q27KRJ5.js:5084
componentUpdateFn @ chunk-3Q27KRJ5.js:5819
run @ reactivity.esm-bundler.js:178
instance.update @ chunk-3Q27KRJ5.js:5860
callWithErrorHandling @ chunk-3Q27KRJ5.js:213
flushJobs @ chunk-3Q27KRJ5.js:411`
![image](https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/77386602/9b042594-09a4-494c-aa53-e5b6f8bf6c26)

**Comment by agracia-foticos** [comment]
i put keepalive : false and runs :( but we lost SPA funcionality

**Comment by AlexLavoie42** [comment]
I believe this is either a bug in nuxt itself, or in your implementation. Removing the module and setting `keepalive` to true has the same issue.
