### ISSUE TITLE
Empty canvas on production

### ISSUE THREAD

**Issue by 0PandaDEV** [AlexLavoie42/Nuxt-Mapbox#57]
I created a little project where a full screen map is displayed, but for some reason it's just blank on production.
In the development environment it works perfectly, but not in production.

Also, how do I make the map 2D?

## How it should look
<img width="1511" alt="image" src="https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/70103896/5445d42e-d2af-42fa-844b-2e1b2f9ad339">

## How it looks in production
![image](https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/70103896/563a1ea6-810a-4f7d-9f20-1e125ec931ce)

**Comment by AlexLavoie42** [comment]
Please check your console for any errors or send a reproduction link. I cannot assist without further details

**Comment by 0PandaDEV** [comment]
Oh, I see it now it says it requires an API access token for the Mapbox API, but I have set one directly in the code that's why I cannot give the code to you, so the token should be in the production build.

![image](https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/70103896/7f7c111f-bf88-49f0-9820-40162f455e34)

**Comment by AlexLavoie42** [comment]
Unfortunately I can't provide much assistance without more details about your production build. Just make sure that your nuxt config is properly making it to your production build, and that your api key is is set correctly in `nuxt.config.ts` like so:

```js
export default defineNuxtConfig({
  modules: [
    'nuxt-mapbox'
  ],
  mapbox: {
    accessToken: '{API_KEY}'
  }
})
```

As for making the map 2d, that is done through the maps [style](https://docs.mapbox.com/mapbox-gl-js/style-spec/)
