### ISSUE TITLE
Feature Request: Add `setRTLTextPlugin` support to module options

### ISSUE THREAD

**Issue by ielb** [AlexLavoie42/Nuxt-Mapbox#59]

**Comment by AlexLavoie42** [comment]
`RTLTextPlugin` will need to be added to module options, and set in the same way as the rest of the options in `plugin.client.ts`:

```js
    const appConfig = useAppConfig() as ExtendedAppConfig
    //@ts-ignore
    mapboxgl.accessToken = appConfig._MAPBOX_CONFIG.accessToken;
    //@ts-ignore
    if (appConfig._MAPBOX_CONFIG.baseApiUrl) mapboxgl.baseApiUrl = appConfig._MAPBOX_CONFIG.baseApiUrl;
    //@ts-ignore
    if (appConfig._MAPBOX_CONFIG.workerUrl) mapboxgl.workerUrl = appConfig._MAPBOX_CONFIG.workerUrl;
    //@ts-ignore
    if (appConfig._MAPBOX_CONFIG.workerCount) mapboxgl.workerCount = appConfig._MAPBOX_CONFIG.workerCount;
    //@ts-ignore
    if (appConfig._MAPBOX_CONFIG.prewarm) mapboxgl.prewarm();
```

Some things to consider if anyone is interested in implementing:
- Should `RTLTextPlugin` type in options be the same `setRTLTextPlugin` parameters? Or maybe just a boolean? (Lazy & callback options? Will RTL text plugin url ever be different?)
- Language option as well? This can be done with `useMapbox` so not entirely necessary. https://docs.mapbox.com/mapbox-gl-js/example/language-switch/

**Comment by AlexLavoie42** [comment]
Added in #73
