### ISSUE TITLE
How to hook into MapboxGeocoder's lifecycle events

### ISSUE THREAD

**Issue by robigan** [AlexLavoie42/Nuxt-Mapbox#71]
How would I go about using MapboxGeocoder component, access the udnerlying geocoder and listen to it's event emitter? At the moment I have to manually grab the map using useMapbox() and add Geocoder's controls to map in JS/TS. I have no diea how to access MapboxGeocoder's `geocoderRef` value so I can hook into it's event emitter

**Comment by AlexLavoie42** [comment]
Currently this is not easily possible. I will work on adding events directly to the geocoder component for v1.5.0 as well as giving direct access to the geocoder using a composable. For now adding the geocoder manually is probably the best solution.

**Comment by AlexLavoie42** [comment]
Added in #73
