### ISSUE TITLE
Nuxt 3.8.1 fails MapboxCustomGeocoder - require is not defined

### ISSUE THREAD

**Issue by agracia-foticos** [AlexLavoie42/Nuxt-Mapbox#75]
![image](https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/77386602/6e98a6d0-a741-4a16-834e-c445327eaa77)

ReferenceError: require is not defined

**Comment by AlexLavoie42** [comment]
Jus to confirm, is this only with 3.8.1 or does it happen on 3.8.0 for you as well?

**Comment by agracia-foticos** [comment]
> Jus to confirm, is this only with 3.8.1 or does it happen on 3.8.0 for you as well?

I don't know... I think in 3.8.0 doesn't crash, but i cant confirm it

**Comment by agracia-foticos** [comment]
> Jus to confirm, is this only with 3.8.1 or does it happen on 3.8.0 for you as well?

**Comment by agracia-foticos** [comment]
@AlexLavoie42 solved!!! Thanks!!!!
