### ISSUE TITLE
Feature Request: reactive layers

### ISSUE THREAD

**Issue by jasonhibbs** [AlexLavoie42/Nuxt-Mapbox#83]
I love where this module is going, so here’s my request for [the soal-mapbox feature](https://github.com/soal/vue-mapbox/blob/e0edd17bde5fe8d1db7f44029e0e3399e2bf35ea/src/components/layer/layerMixin.js#L88-L116) I use the most.

For paint, layout, and filter, soal-mapbox used watchers to update the map. Here’s an example:

```
    if (this.layer.paint) {
      this.$watch(
        "layer.paint",
        function(next) {
          if (this.initial) return;
          if (next) {
            for (let prop of Object.keys(next)) {
              this.map.setPaintProperty(this.layerId, prop, next[prop]);
            }
          }
        },
        { deep: true }
      );
    }
```

**Comment by AlexLavoie42** [comment]
Totally missed watching the layer properties. I am doing this for most other components.

Would be pretty easy to just copy what is used in [MapboxMap.vue](https://github.com/AlexLavoie42/Nuxt-Mapbox/blob/47c9dcaf566d4eb8ce6a55c714d65cfca142caeb/src/runtime/components/Map.vue#L205) over to the layer component for properties that can be modified.

PR would be greatly appreciated if possible!
