### ISSUE TITLE
How to? Display a popup on hover

### ISSUE THREAD

**Issue by martnst** [AlexLavoie42/Nuxt-Mapbox#94]
Hey *, 

How can I build a popup on hover with the nuxt wrapper? 
Here is the docs by Mapbox for it: 
https://docs.mapbox.com/mapbox-gl-js/example/popup-on-hover/

Cheers

**Comment by AlexLavoie42** [comment]
Simplest way is to use the `mouseenter` & `mouseleave` events on your layer and copy the Mapbox implementation.
https://alexlavoie42.github.io/Nuxt-Mapbox/usage/accessing-the-map#events
