### ISSUE TITLE
Missing 'style.load' event support ?

### ISSUE THREAD

**Issue by Theo-Rige** [AlexLavoie42/Nuxt-Mapbox#98]
How can I use the 'style.load' event : [https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:style.load](https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:style.load) ?

**Comment by AlexLavoie42** [comment]
I think this event just got missed, although there may have been a good reason to not have it that I can't remember. I will try to add it for the next update.

For now you can do this:
```js
useMapboxBeforeLoad((map) => {
    map.on('style.load', () => {...})
})
```
